services:

  redis:
    container_name: redis-container-flnks
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"   # RedisInsight (WEB)
    restart: unless-stopped

  app:
    build:
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
