name: Docker Build

on:
  pull_request:
    branches:
      - master
    paths:
      - 'docker/**'
      - 'app/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAG: flnks-1.0.12
      REPOSITORY: my-ecr

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH  # adiciona poetry no PATH

      - name: Install dependencies
        run: poetry install --no-root

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Push Docker image to ECR
        run: |
          poetry run python3 services/push_docker_image.py

      - name: Deploy Lambda
        env:
          FUNCTION_NAME: flnks_lambda
        run: |
          poetry run python3 services/deploy_lambda.py